### PR TITLE
Freivald -> Freivalds (Typo fix)

### PR DESCRIPTION
**Pull request by r-kellerm**
Typo fix -
Freivalds' algorithm is name after Rūsiņš Mārtiņš Freivald**s**
(Should be changed in the paper as well)

### CODE REVIEW

**Comment by ftramer** [comment]
Thanks a lot for spotting this! Can't believe I been making this mistake everywhere in the past few months... Cheers!

**Comment by r-kellerm** [comment]
Thank you.
I think this ideas are brilliant. 
(Hope this is ok to ask a question here - have you considered to use the "blinding" technique to keep the weights private instead of the input?)

**Comment by ftramer** [comment]
Unfortunately, using the blinding technique for weights doesn't quite work out. 

Say you have a matrix product X*W, between inputs X and weights W.

To blind the inputs, we sample some random R and compute R*W ahead of time (offline phase). Then, when an input X comes in (online phase), we outsource X+R, get Z=(X+R)*W, and subtract the precomputed R*W to recover the product X*W.

If we were to blind the weights, the untrusted device gets W'=W+R. Suppose we don't blind inputs for simplicity. Then, we send X to the device and obtain X*W' = X*W + X*R. Now, to recover X*W we'd need to know X*R, which is where the problem lies. We cannot precompute X*R as we don't know X in advance, and computing X*R "online" defeats the purpose of outsourcing as it is as expensive to compute as X*W.

**Comment by r-kellerm** [comment]
Oh, of course.
I guess it will still be possible in a multi-party setting with 2 non-colluding accelerators, right?

**Comment by ftramer** [comment]
Yes, although blinding both the weights and the inputs would be tricky.

**Pull request merged**
